# Generated by Django 4.1.5 on 2023-01-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('image', models.CharField(max_length=300)),
                ('available', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(related_name='items', to='categories.category')),
            ],
        ),
    ]
